name: Integração Contínua

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --no-restore

      - name: Verificar código (Lint)
        run: dotnet format --verify-no-changes

      - name: Executar testes
        run: dotnet test --no-build --verbosity normal
